# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e4932013558549de0ab172c2dd407dcd8c56e4d9266d68864742fb31ca6e78a85d7db8bd5f3c4df71e7c6fafc890ffcd68f8ddea3913561c413794751286724

test:
  secret_key_base: 58055daa68bebb82646f01eb27e9d7ebae3efd6cae5153b72f386036a0ea214db44957cca0bf2ffc82ba4cb072441eb13217e15fee8ce26125658957341118a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
